version: '3'

services:
  www:
    build: ./frontend
    ports:
      - "${WWW_PORT:-8080}:${WWW_PORT:-8080}"
    volumes:
      - ./www/src/:/app/
    depends_on:
      - api
    environment:
      WWW_PORT: ${WWW_PORT:-8080}

  api:
    build: ./api
    hostname: ${API_HOSTNAME:-play.api}
    ports:
      - "${API_PORT:-9000}:${API_PORT:-9000}"
    volumes:
      - ./api/src/:/app/
    depends_on:
      - redis
    environment:
      API_HOSTNAME: ${API_HOSTNAME-play.api}
      API_PORT: ${API_PORT:-9000}

  redis:
    image: "redis:alpine"
    hostname: ${REDIS_HOSTNAME:-redis}
    ports:
        - "6379:6379"
    environment:
      REDIS_HOSTNAME: ${REDIS_HOSTNAME:-redis}
